add test groovy to test
Signed-off-by: Jenny Li <jing.li@zilliz.com>

diff --git a/.github/workflows/jenkins-checker.yaml b/.github/workflows/jenkins-checker.yaml
--- a/.github/workflows/jenkins-checker.yaml
+++ b/.github/workflows/jenkins-checker.yaml
@@ -26,16 +26,16 @@ jobs:
           JENKINS_CRUMB=`curl "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"`
 
           function validate(){
-              local file_path=${1:-Jenkinsfile}
-              response=$(curl -X POST -H $JENKINS_CRUMB -F "jenkinsfile=<${file_path}" $JENKINS_URL/pipeline-model-converter/validate)
-              echo ${response}
-              result=$(echo $response | grep "Error")
-              if [[ ${result} != "" ]]
-              then
-                  echo "Validate ${file_path} failed !"
-                  
-                  exit 1  
-              fi
+            local file_path=${1:-Jenkinsfile}
+            response=$(curl -X POST -H $JENKINS_CRUMB -F "jenkinsfile=<${file_path}" $JENKINS_URL/pipeline-model-converter/validate)
+            
+            if [[ ${response} =~ "Error"  ]]
+            then
+                echo " ${response}"
+                echo "Validate ${file_path} failed !"
+                
+                exit 1  
+            fi
           }
 
           for file in build/ci/jenkins/*
