[skip ci] Add github action check for jenkinsfile
Signed-off-by: Jenny Li <jing.li@zilliz.com>

diff --git a/.github/workflows/jenkins-checker.yaml b/.github/workflows/jenkins-checker.yaml
--- a/.github/workflows/jenkins-checker.yaml
+++ b/.github/workflows/jenkins-checker.yaml
@@ -14,4 +14,43 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v2
+      - name: Validate Jenkinsfile
+        shell: bash
+        run: |
+          JENKINS_URL=https://ci.milvus.io:18080/jenkins
+          # JENKINS_CRUMB is needed if your Jenkins controller has CRSF protection enabled as it should
+          JENKINS_CRUMB=`curl "$JENKINS_URL/crumbIssuer/api/xml?xpath=concat(//crumbRequestField,\":\",//crumb)"`
+
+          function validate(){
+              local file_path=${1:-Jenkinsfile}
+              response=$(curl -X POST -H $JENKINS_CRUMB -F "jenkinsfile=<${file_path}" $JENKINS_URL/pipeline-model-converter/validate)
+              echo ${response}
+              result=$(echo $response | grep "Error")
+              if [[ ${result} != "" ]]
+              then
+                  echo "Validate ${file_path} failed !"
+                  
+                  exit 1  
+              fi
+          }
+
+          for file in build/ci/jenkins/*
+          do
+              if [ -f "$file"  ] 
+              then 
+                  echo "$file"
+                  file_name=$(basename "$file")
+
+                  if echo "${file_name}" | grep -q -E '\.groovy$'
+                  then 
+                      echo "Validate groovy file ${file_name}"
+                      validate $file
+                  elif [[ "${file_name}" == "Jenkinsfile" ]]
+                  then
+                      echo "Validate Jenkinsfile"
+                      validate $file    
+                  fi
+              fi
+          done
+          
     
